on:
  push:
    branches: [ main ]
  pull_request:
  pull_request_target:

name: CI

jobs:
  install-deps:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - name: Install locked dependencies
        run: npm ci

      - name: Cache dependencies
        uses: actions/cache@v2
        id: cache-deps
        with:
          path: |
            ~/.cache/Cypress
            node_modules
            client/node_modules
            server/node_modules
          key: ${{ github.sha }}

  e2e:
    name: End-to-end tests
    runs-on: ubuntu-latest
    needs: install-deps
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Restore cached dependencies
        uses: actions/cache@v2
        id: restore-deps
        with:
          path: |
            ~/.cache/Cypress
            node_modules
            client/node_modules
            server/node_modules
          key: ${{ github.sha }}

      - name: Setup Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - name: Run Cypress
        id: cypress
        uses: cypress-io/github-action@v2
        with:
          install: false
          video: false
          start: npm run start:ci
          wait-on: "http://localhost:3000, http://localhost:4320/swagger/"
        env:
          CI: true

  add_labels:
    needs: e2e
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: |
            task-completed

